### PR TITLE
Fix problems with blob field filter deserialization

### PR DESCRIPTION
**Pull request by kbolashev**
Before this PR deserializing a query with a blob field filter on it would throw the following error:
```
TypeError: string argument without an encoding
```
Because it was trying to call `bytes("b'<whatever_value_was_there>'")`

This PR fixes this behavior and correctly deserializes the binary values. As a fallback if I don't get the `b'`/`b"`-prefix, I turn the whole value into the byte array

Tests for the custom deserializer + a loop of deserialize->serialize included

### CODE REVIEW

**Review by simonlsk — CHANGES_REQUESTED** [review]
Thanks, this will solve the current issue with deserialization!
I think we should also have a dedicated handling for bytes at serialization time. 
WDYT?

**Comment by kbolashev** [comment]
> Thanks, this will solve the current issue with deserialization! I think we should also have a dedicated handling for bytes at serialization time. WDYT?

Sure, what do we want to do with those? gzip -> base64, same as uploading?
Means I'll have to also do the reverse here then

**Comment by simonlsk** [comment]
> Sure, what do we want to do with those? gzip -> base64, same as uploading?
Means I'll have to also do the reverse here then

Sorry, I mean when running the `saveDataset` mutation, the value in `filter.query.filter.value` should be an empty string when the field type is blob, and the query is `is_null`.

**Review by simonlsk — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
